gtfs.static-props.data-dir=data/gtfs_static

logging.level.it.roma.gtfs.gtfs_monitor.controller=DEBUG
logging.level.it.roma.gtfs.gtfs_monitor.service.StaticGtfsUpdater=DEBUG

app.cors.allowed-origins=http://localhost:4200,http://127.0.0.1:4200,http://localhost:4203,http://127.0.0.1:4203,http://localhost:5173,http://127.0.0.1:5173,http://192.168.1.62:4203

journey.otp.base-url=http://localhost:8081
