gtfs.static-props.data-dir=/app/data/gtfs_static

logging.level.root=INFO
logging.level.it.roma.gtfs.gtfs_monitor=INFO

app.cors.allowed-origins=https://wemoveroma.com,https://www.wemoveroma.com

journey.otp.base-url=http://otp:8081
