spring.application.name=gtfs-monitor
server.port=8080

gtfs.static-props.url=https://romamobilita.it/sites/default/files/rome_static_gtfs.zip
gtfs.static-props.refresh-millis=3600000

gtfs.realtime.trip-updates-url=https://romamobilita.it/sites/default/files/rome_rtgtfs_trip_updates_feed.pb
gtfs.realtime.vehicle-positions-url=https://romamobilita.it/sites/default/files/rome_rtgtfs_vehicle_positions_feed.pb
gtfs.realtime.service-alerts-url=https://romamobilita.it/sites/default/files/rome_rtgtfs_service_alerts_feed.pb
gtfs.realtime.refresh-millis=5000

spring.codec.max-in-memory-size=104857600

server.compression.enabled=true
server.compression.mime-types=application/json,text/plain,text/event-stream
server.compression.min-response-size=1024

# OpenTripPlanner
journey.otp.enabled=true
journey.otp.plan-path=/routers/default/plan

# Rail live info
rail.viaggiatreno.enabled=true
rail.viaggiatreno.base-url=https://www.viaggiatreno.it
rail.viaggiatreno.api-base-url=http://www.viaggiatreno.it
